version: '2'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /opt/flaskdevops-heroku-mysql:/counter_app
    links:
      - db:mysql
    container_name: counterapp_web_1
    depends_on:
      - db
    environment:
        PORT: 5000
        DB_USERNAME: root
        DB_PASSWORD: rootpass
        DB_HOST: mysql
        DATABASE_NAME: counter
  db:
    image: mysql:5.7
    restart: always
    container_name: counterapp_db_1
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: counter
